### ISSUE TITLE
amd64 version missing for java 17 mariner

### ISSUE THREAD

**Issue by vonElfvin** [microsoft/openjdk-docker#102]
I've ran:

`FROM --platform=linux/amd64 mcr.microsoft.com/openjdk/jdk:17-mariner` probably 1000 times and now it stopped working, if I change to `FROM mcr.microsoft.com/openjdk/jdk:17-mariner` it works but then it defaults to my device's version which is ARM.

**Comment by askew** [comment]
This has broken our CI pipeline. sha256:e848d8056c3... is not the listed digest for 17-mariner, maybe missing a base layer?
```
docker pull mcr.microsoft.com/openjdk/jdk:17-mariner
17-mariner: Pulling from openjdk/jdk
manifest for mcr.microsoft.com/openjdk/jdk:17-mariner not found: manifest unknown: manifest sha256:e848d8056c304a0b18c1a6eae0c27943949fe381f761bb5597e254f81245fb14 is not found
```

**Comment by karianna** [comment]
There's also been an internal mail thread on this where we've been unable to replicate, so we're suspecting it's a regional MCR CDN issue, for folks watching an internal support mailing list has been recommended to chase that down. CC @brunoborges

**Comment by askew** [comment]
A new version was pushed to the registry yesterday and it appears to be working again now.

**Comment by brunoborges** [comment]
That's due to our weekly rollout.

I believe the original issue was related to some caching.

Glad it is all fine now!
