### ISSUE TITLE
Provide regular updates of Docker images (was: CVE's CBL-Mariner)

### ISSUE THREAD

**Issue by ingmars1709** [microsoft/openjdk-docker#24]
Hi,

According to https://github.com/microsoft/CBL-Mariner/releases/tag/1.0.20220307-1.0
there are quite some CVE's fixed.

Are these incorporated into the **mcr.microsoft.com/openjdk/jdk:11-mariner** image as well?

**Comment by gdams** [comment]
This is a good question. We don't currently rebuild the base images until a new OpenJDK release is available. We likely need to listen to changes in the base images and rebuild when they do.

**Comment by karianna** [comment]
@milderhc is listening in on security pointy releases of Linux distro's possible?  Intriguing thought.

**Comment by ingmars1709** [comment]
Is this something we can expect to be solved in the near future? 
We are relying heavily on this image and it generates a lot of High Findings in Azure Security portal.

**Comment by karianna** [comment]
> Is this something we can expect to be solved in the near future? We are relying heavily on this image and it generates a lot of High Findings in Azure Security portal.

We're discussing this internally so we can put out a public policy and will respond back here in the next week or so.

**Comment by d3r3kk** [comment]
We can certainly create a _scheduled_ trigger in our GH/AzDO that would simply inspect the CBL-Mariner releases and take action if a release we've not seen before shows up. I'll see if I can rig something up in the next few days.

**Comment by brunoborges** [comment]
@d3r3kk mind if we keep this issue open until this is addressed?

**Comment by brunoborges** [comment]
We will update weekly, starting on or before the July PSU 2022.
