### ISSUE TITLE
Build more often, fix security issues

### ISSUE THREAD

**Issue by mblaschke-daimlertruck** [microsoft/openjdk-docker#35]
The published container images for openjdk are shipped with open security issues and were last pushed at 06/22/2022.

As a customer i expect regularly updates of container image so please update your base images more often (eg. every week or on a daily basis).

**Comment by karianna** [comment]
@d3r3kk I know we recently improved this cadence can you comment here?

**Comment by d3r3kk** [comment]
I will double-check tomorrow with the team and see where we're at, or if our current tactic has fallen over somehow.

Detail: We have added a pipeline that runs daily (perhaps more than once per day) that rebuilds images we publish locally on an agent, compares that built image to the currently published image on MCR, and then re-publishes when a difference is detected.

If this approach has failed I am certainly interested into learning why!

@mblaschke-daimlertruck, can you please add some specific details about the open security issues you are seeing on our currently published images (image name, tag, and CVE would be highly appreciated!).

My team and I would then use that information to do a thorough dig through our pipeline to see why it may be failing, and why it may have missed these problems so we can improve upon our current state.

**Comment by d3r3kk** [comment]
I will double-check tomorrow with the team and see where we're at, or if our current tactic has fallen over somehow.

Detail: We have added a pipeline that runs daily (perhaps more than once per day, I cannot remember offhand) that rebuilds images we publish locally on an agent, compares that built image to the currently published image on MCR, and then re-publishes when a difference is detected.

@mblaschke-daimlertruck, can you please be specific about the open security issues you are seeing on our currently published images? I'd love to record that and do a thorough dig through our pipeline to see why it may be failing.

**Comment by mblaschke-daimlertruck** [comment]
Just the normal distribution updates from ubuntu, there was a security issue in openssl.

(Yes can be fixed with apt update && apt upgrade but it would good if the images are rebuild more often)

**Comment by d3r3kk** [comment]
Ha! We discovered the issue. Thank you for bringing it up @mblaschke-daimlertruck!

We are currently assessing the _base image_ we build on top of, against the _published image_ we create. If the two differ (we compare the hash of each common layer), then we republish. We did not previously _rebuild_ our image locally to evaluate these differences which means we miss distribution-level package-manager updates.

You are correct that it is a simple `apt-get update -qq && apt-get upgrade -qq -y` and that will remain a workaround in perpetuity (for Ubuntu). We do want to ensure that our published images are as up-to-date as possible, so we'll push a change to our process in the coming weeks (it's OpenJDK PSU release season at the moment, so I suspect it will take us a week or two to deliver on this update).

I'll close this issue once we put the process in place with this new strategy implemented. For now, please do use the workaround.

**Comment by joe-braley** [comment]
Hi team, we have streamlined our process and updated our cadence to build images once per week. 

If we still experience issues with packages not being updated appropriately then we can re-open this issue. 

Thanks.
