### ISSUE TITLE
Add instructions on how to include font-config package to Distroless

### ISSUE THREAD

**Issue by floriankoch** [microsoft/openjdk-docker#43]
We got such exeptions when using the distroless images with one of our applications

What is missing here?
 
```
ava.lang.NullPointerException: null
          at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
          at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
          at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
          at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
          at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:379)
          at java.base/java.security.AccessController.doPrivileged(Native Method)
          at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:324)
          at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
          at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
```

**Comment by karianna** [comment]
@floriankoch The distroless images likely do not contain the font packages.  Is there a particular font that your application is expecting to use?

**Comment by floriankoch** [comment]
@karianna   SansSerif in our case

**Comment by karianna** [comment]
@brunoborges - I see three options here:

* Ask distroless base image provider to provide a minimum set of fonts
* Provide docs on how to add for end users
* Bundle fonts with OpenJDK (which I think typically don't do as we prefer to allow the O/S to do so)

Thoughts?

**Comment by floriankoch** [comment]
@karianna   any news here?

**Comment by brunoborges** [comment]
@floriankoch we are editing the documentation this week. 

As for what we will be adding, you can see this example on how to add a package on a build-layer in a Dockerfile, and then copy installed packages to the final distroless image.

https://github.com/microsoft/openjdk-docker/blob/main/docker/distroless/Dockerfile.msopenjdk-17-jdk#L20-L27

**Comment by brunoborges** [comment]
@floriankoch can you please provide a sample Java code that tries to load the extra fonts? I'd like to test the instructions.

**Comment by floriankoch** [comment]
@brunoborges   the error comes from a third party application (camunda) 

I added this to my multi stage dockerfile

`RUN mkdir /dejavu \
    && tdnf install -y --releasever=2.0 --installroot /dejavu dejavu-sans-fonts
RUN mkdir /fontconfig \
    && tdnf install -y --releasever=2.0 --installroot /fontconfig fontconfig
RUN mkdir /freetype \
    && tdnf install -y --releasever=2.0 --installroot /freetype freetype

# Clean up
RUN rm -rf /dejavu/etc/dnf \
    && rm -rf /dejavu/run/* \
    && rm -rf /dejavu/var/cache/dnf

RUN rm -rf /fontconfig/etc/dnf \
    && rm -rf /fontconfig/run/* \
    && rm -rf /fontconfig/var/cache/dnf \
    && find /fontconfig/var/log -type f -size +0 -delete

RUN rm -rf /freetype/etc/dnf \
    && rm -rf /freetype/run/* \
    && rm -rf /freetype/var/cache/dnf \
    && find /freetype/var/log -type f -size +0 -delete
...

COPY --from=builder /dejavu /
COPY --from=builder /fontconfig /
COPY --from=builder /freetype /
`

and use this programm to test if java find the fonts

`import java.awt.*;

public class FontTest {

    public static void main(String[] args) {
        String[] names = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();

        System.out.println("Found " + names.length + " fonts:");

        for (String name : names) {
            System.out.println(name);
        }
    }
}`

looks good so far ... now we test with the application

`docker run -it -v $PWD:/tmp test:1 java -cp /tmp FontTest
Found 8 fonts:
DejaVu Sans
DejaVu Sans Condensed
DejaVu Sans Light
Dialog
DialogInput
Monospaced
SansSerif
Serif`

**Comment by floriankoch** [comment]
Now all is working, thx for your help
