### ISSUE TITLE
Publish AArch64 (Arm64) container images

### ISSUE THREAD

**Issue by brunoborges** [microsoft/openjdk-docker#46]
If you would like to see AArch64 (Arm64) images published, please let us know by commenting or upvoting on this issue.

**Comment by iemejia** [comment]
I think this starts to make more and more sense with the Azure supporting arm64 processors + the new Windows Dev Kit (arm64)  machine

**Comment by Curtisjk** [comment]
+1 for this. We are looking to use Microsoft OpenJDK images primarily in a macOS environment where we need to support both `amd64` and `aarch64`

**Comment by brunoborges** [comment]
We do now publish `arm64` images.

Enjoy!

https://learn.microsoft.com/en-gb/java/openjdk/containers#architectures
