### ISSUE TITLE
Wrong base image for Ubuntu images

### ISSUE THREAD

**Issue by HenrikBacher** [microsoft/openjdk-docker#84]
The Ubuntu images are still published using Ubuntu 20.04 even though the source states that's it's published with 22.04, in this example should the 17-ubuntu images, but I see the same issue with 11-ubuntu & 21-ubuntu
![image](https://github.com/microsoft/openjdk-docker/assets/231445/57d4cb5f-3e73-43ff-b2c4-fb7f6c162399)

**Comment by joe-braley** [comment]
Hi @HenrikBacher, thank you for bringing this to our attention!

We have re-built the images in question, and we are now on the correct base image. Please see the output below.

![image](https://github.com/microsoft/openjdk-docker/assets/106336504/007c431d-3de4-4325-9861-cc946e72b75a)
![image](https://github.com/microsoft/openjdk-docker/assets/106336504/12450c7f-2cb3-42dc-92cf-e8836823e68b)
![image](https://github.com/microsoft/openjdk-docker/assets/106336504/52196814-b697-443f-a6e5-9d5cde30d585)

If you could kindly verify this on your end that would be appreciated. Thanks!

**Comment by HenrikBacher** [comment]
Yes, the image use the right base image now. I'm curious though, how is the image updated? The base image in the dockerfile was updated months ago, while it haden't propergated to the image in MCR?

**Comment by joe-braley** [comment]
Previously we updated our docker images once per week and have recently increased that cadence to three times per week.

If this issue is resolved to your satisfaction, please kindly close this issue. 

Thanks!
