### ISSUE TITLE
Sign docker images

### ISSUE THREAD

**Issue by theodor-franke** [microsoft/openjdk-docker#90]
To enable a full chain of trust and verify the docker image it would be relay beneficial that you sign your images.  
Google distroless images for example are signed using [cosign](https://github.com/sigstore/cosign). 
[Link to google distroless verification instruction](https://github.com/GoogleContainerTools/distroless?tab=readme-ov-file#how-do-i-verify-distroless-images)

**Comment by karianna** [comment]
@d3r3kk - What is the std practice for MSFT images here?

**Comment by d3r3kk** [comment]
This is indeed something that MSFT does internally, and we will adopt the practice over the coming month or so. @Luigi96 may be able to get to it with our team.

**Comment by joe-braley** [comment]
The current iteration of our images should be signed. Their signatures can be discovered using the following command:
![image](https://github.com/microsoft/openjdk-docker/assets/106336504/e47de80b-8fc9-4ba9-ada7-cafb5cab0b39)
![image](https://github.com/microsoft/openjdk-docker/assets/106336504/f2d31ef5-fbf7-4510-b526-7ad822b14509)

If there is any issues observed, please let us know!

**Comment by karianna** [comment]
^^ @theodor-franke

**Comment by janigabor** [comment]
Indeed, the signature can be discovered with oras. Not sure however how to verify the signature? Notation seems not to be able to find the signatures.

![image](https://github.com/microsoft/openjdk-docker/assets/22069493/4cd9c59a-bbab-4136-adf2-96da13c55845)

**Comment by karianna** [comment]
@joe-braley Can you confirm the verification steps and whether we have that listed on our docs page (download area).

**Comment by janigabor** [comment]
Pulling the image with content trust turned on without any additional settings does not work either:

![image](https://github.com/microsoft/openjdk-docker/assets/22069493/849e4c85-e03f-43a9-bee9-f7daaec538c3)

Any documentation regarding verifying the signatures would be greatly appreciated

**Comment by joe-braley** [comment]
Hey folks! I have reviewed our recommended process to verify the signatures. Please follow the steps below:

Verifying Microsoft's build of OpenJDK image signatures:

- What you will need:
  - [Notation CLI
](https://notaryproject.dev/docs/user-guides/installation/cli/)  
  - [msft_supply_chain.crt
](https://www.microsoft.com/pkiops/certs/Microsoft%20Supply%20Chain%20RSA%20Root%20CA%202022.crt)    
    - Download and save to your local machine (e.g., msft_supply_chain.crt)
- Steps:
  - Add the certificate to the trust store.
	```bash
 		notation cert add --type ca --store supplychain msft_supply_chain.crt
 	```
  - Configure trust policies.
    - 	Create a trustpolicy.json with the following content:
    ```json
        {
            "version": "1.0",
            "trustPolicies": [
                {
                    "name": "supplychain",
                    "registryScopes": [ "mcr.microsoft.com/openjdk/jdk" ],
                    "signatureVerification": {
                        "level" : "strict"
                    },
                    "trustStores": [ "ca:supplychain" ],
                    "trustedIdentities": [
                        "x509.subject: CN=Microsoft SCD Products RSA Signing,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US"
                    ]
                }
            ]
        }
    ```
  -  Import the trust policy.
      ```bash
 		notation policy import trustpolicy.json
      ```
  - Verify the image.
    ```bash
 		export NOTATION_EXPERIMENTAL=1 # must be set!
 		notation verify --allow-referrers-api mcr.microsoft.com/openjdk/jdk:11-mariner
    ```
    
    You then should see the following output
    
![image](https://github.com/user-attachments/assets/c0219596-e4e1-487c-8b0b-1d4fcbe255ca)

Please let us know if there are any issues with the content above!

**Comment by karianna** [comment]
Once verified, @brunoborges to determine if we add this to our official doc set.
